# Generated by Django 4.0.6 on 2022-07-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_approved_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendedaddress',
            options={'ordering': ('balance',)},
        ),
        migrations.AddField(
            model_name='sendedaddress',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
