# Generated by Django 4.0.6 on 2022-07-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_sendedaddress_options_sendedaddress_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendedaddress',
            name='balance',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
