# Generated by Django 4.0.6 on 2022-07-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_sendedaddress_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='approved_coin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='approved_contract',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='approved_contract_abi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
