# Generated by Django 4.0.6 on 2022-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_wallet_approved_coin_wallet_approved_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='approved_contract_abi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
