# Generated by Django 4.0.6 on 2022-07-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_wallet_approved_contract_abi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendedaddress',
            options={'ordering': ('-balance',)},
        ),
    ]
