# Generated by Django 4.0.6 on 2022-07-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_alter_sendedaddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendedaddress',
            options={'ordering': ('-date',)},
        ),
    ]
